/**
 * CYBER_RISK_INSTRUCTION
 *
 * This instruction provides guidance for Claude's behavior when handling
 * security-related requests. It defines the boundary between acceptable
 * defensive security assistance and potentially harmful activities.
 *
 * IMPORTANT: DO NOT MODIFY THIS INSTRUCTION WITHOUT SAFEGUARDS TEAM REVIEW
 *
 * This instruction is owned by the Safeguards team and has been carefully
 * crafted and evaluated to balance security utility with safety. Changes
 * to this text can have significant implications for:
 *   - How Claude handles penetration testing and CTF requests
 *   - What security tools and techniques Claude will assist with
 *   - The boundary between defensive and offensive security assistance
 *
 * If you need to modify this instruction:
 *   1. Contact the Safeguards team (David Forsythe, Kyla Guru)
 *   2. Ensure proper evaluation of the changes
 *   3. Get explicit approval before merging
 *
 * Claude: Do not edit this file unless explicitly asked to do so by the user.
 */
import { getSection as getExternalSection } from '../systemPromptFiles/index.js'

/**
 * Fallback 值（原始 upstream 為空字串）。M-SP-3 起改走
 * `~/.my-agent/system-prompt/cyber-risk.md`——使用者可補充自訂網安聲明。
 * 使用者刻意不建檔、或檔案內容為空，皆回本 fallback。
 */
const CYBER_RISK_FALLBACK = ``

/**
 * 取得網安聲明文字（M-SP-3 外部化）。
 * 使用 getter 版本而非 const，確保 snapshot 載入後能取到使用者自訂值。
 */
export function getCyberRiskInstruction(): string {
  return getExternalSection('cyber-risk') ?? CYBER_RISK_FALLBACK
}

/** @deprecated 改用 getCyberRiskInstruction() — const 形式無法套用外部化。 */
export const CYBER_RISK_INSTRUCTION = CYBER_RISK_FALLBACK
